### ISSUE TITLE
Manage dependency versions

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/nfsbroker#5]
For users who don't deploy this app as a BOSH job, it would be useful to capture dependency versions using `dep`. Running `go get ./...` doesn't work at the moment because `brokerapi` vendors its dependencies, leading to conflicting copies of `lager`. I could grab the current dependency versions by checking out `nfs-volume-release` and copying its `src` directory to `vendor` or setting a custom `GOPATH`, but that feels like a hack.

Would you all be open to tracking dependencies with `dep`? I'd be happy to run `dep init` and send a patch 😃.

**Comment by julian-hj** [comment]
Hey, sorry for the super slow response.  My only hesitation here is that we don't like to have things in our code that we don't test in ci, and we already have many flavors of nfs build and deployment, so adding yet another one is a bit painful.

By convention, because we use bosh for mostly everything (even for cf-pushing the broker) we treat nfs-volume-release as a GOPATH and just gather all the dependencies in the correct versions as git submodules.  You should not have to set a custom GOPATH yourself, because we already do that in `.envrc`. If you just type `direnv allow` in the nfs-volume-release directory, then your GOPATH will get set when you `cd` into nfs-volume-release and unset when you `cd` back out.

**Comment by julian-hj** [comment]
Closing this, as we have no plans to fix it.
